language: node_js
dist: trusty
sudo: required
mono: none
node_js: 
  - 7
branches:
  only:
    - master
before_script:
  - chmod -R a+x ci
  - npm install -g @angular/cli
  - npm install -g karma
script:
  - ./ci/travis-build.sh
after_success:
  - ./ci/after-success.sh
notifications:
  email:
    on_success: never
    on_failure: always