language: node_js
dist: trusty
sudo: required
mono: none
node_js: 
  - 6
branches:
  only:
    - master
before_script:
  - chmod -R a+x scripts
  - npm install -g --silent @angular/cli
script:
  - ./scripts/travis-build.sh
after_success:
  - ./scripts/after-success.sh
notifications:
  email:
    on_success: never
    on_failure: always
